// Se crea una interface y no una clase porque queremos ponerle el tipo a la respuesta de pokeapi.co
// No queremos manipular la data.

// Generated by https://quicktype.io

export interface PokeResponse {
  count: number;
  next: string;
  previous: null;
  results: Result[];
}

export interface Result {
  name: string;
  url: string;
}
